#pragma once

#include <WinSock2.h>


const INT16 PACKET_HEAER_SIZE = 5;
const INT MAX_USER_ID_BYTE_LENGTH = 33;
const INT MAX_USER_PW_BYTE_LENGTH = 33;
const INT MAX_CHAT_MSG_SIZE = 257;
const UINT32 MAX_LENGTH = 1024;

enum class PACKET_ID : UINT16
{
	DEV_ECHO = 1,

	// ·Î±×ÀÎ
	LOGIN_REQ = 201,
	LOGIN_RES = 202,

	ROOM_ENTER_REQ = 210,
	ROOM_ENTER_RES = 211,
	ROOM_NEW_USER_NOTIFY = 212,
	ROOM_USER_LIST_NOTIFY = 213,

	ROOM_LEAVE_REQ = 220,
	ROOM_LEAVER_RES = 221,
	ROOM_LEAVE_USER_NOTIFY = 222,

	ROOM_CHAT_REQ = 230,
	ROOM_CHAT_RES = 231,
	ROOM_CHAT_NOTIFY = 232,
};

enum class ERROR_CODE : INT16
{
	ERROR_NONE = 0,

	ERROR_CODE_USER_MGR_INVALID_USER_UNIQUEID = 110,
	ERROR_CODE_PUBLIC_CHANNEL_IN_USER = 111,
	ERROR_CODE_PUBLIC_CHANNEL_INVALID_NUMBER = 112,
};